/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project1;

public class App {
    public static void main(String[] args) {
        Stack inStack = new Stack(Operator);
    }
}
